package com.yangyongwen.zhihu3.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yangyongwen.zhihu3.dao.Story;

import com.yangyongwen.zhihu3.dao.StoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storyDaoConfig;

    private final StoryDao storyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storyDaoConfig = daoConfigMap.get(StoryDao.class).clone();
        storyDaoConfig.initIdentityScope(type);

        storyDao = new StoryDao(storyDaoConfig, this);

        registerDao(Story.class, storyDao);
    }
    
    public void clear() {
        storyDaoConfig.getIdentityScope().clear();
    }

    public StoryDao getStoryDao() {
        return storyDao;
    }

}
