package com.yangyongwen.zhihu3.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yangyongwen.zhihu3.dao.Story;
import com.yangyongwen.zhihu3.dao.Image;
import com.yangyongwen.zhihu3.dao.TopStory;

import com.yangyongwen.zhihu3.dao.StoryDao;
import com.yangyongwen.zhihu3.dao.ImageDao;
import com.yangyongwen.zhihu3.dao.TopStoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storyDaoConfig;
    private final DaoConfig imageDaoConfig;
    private final DaoConfig topStoryDaoConfig;

    private final StoryDao storyDao;
    private final ImageDao imageDao;
    private final TopStoryDao topStoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storyDaoConfig = daoConfigMap.get(StoryDao.class).clone();
        storyDaoConfig.initIdentityScope(type);

        imageDaoConfig = daoConfigMap.get(ImageDao.class).clone();
        imageDaoConfig.initIdentityScope(type);

        topStoryDaoConfig = daoConfigMap.get(TopStoryDao.class).clone();
        topStoryDaoConfig.initIdentityScope(type);

        storyDao = new StoryDao(storyDaoConfig, this);
        imageDao = new ImageDao(imageDaoConfig, this);
        topStoryDao = new TopStoryDao(topStoryDaoConfig, this);

        registerDao(Story.class, storyDao);
        registerDao(Image.class, imageDao);
        registerDao(TopStory.class, topStoryDao);
    }
    
    public void clear() {
        storyDaoConfig.getIdentityScope().clear();
        imageDaoConfig.getIdentityScope().clear();
        topStoryDaoConfig.getIdentityScope().clear();
    }

    public StoryDao getStoryDao() {
        return storyDao;
    }

    public ImageDao getImageDao() {
        return imageDao;
    }

    public TopStoryDao getTopStoryDao() {
        return topStoryDao;
    }

}
